version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: my-platform-db
    environment:
      POSTGRES_DB: my_platform
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d my_platform"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 
